### PR TITLE
Consider playerHealModifier as well as GetHealModifier in heal calculations

### PR DESCRIPTION
**Pull request by Dog**
Attempts to fix https://github.com/Azilroka/LibHealComm-4.0/issues/23

### CODE REVIEW

**Comment by Dog** [comment]
When cast on blood fury'd orc w/o power infusion - 0.5 modifier
When cast on blood fury'd orc with power infusion - 0.6 modifier
When cast w/o blood fury and w/o power infusion - 1 modifier
When cast w/o blood fury and power infusion - 1.2 modifier

**Comment by Dog** [comment]
After a lot of discussion in a discord channel, I've seen the argument that this is a problem with most frames not properly implementing HealComm support and they should instead be using `GetHealModifier` similar to the below:
https://github.com/dev7355608/ClassicHealPrediction/blob/629ba9eaba0a26fbe38b2a4730b5327608e1da58/ClassicHealPrediction.lua#L327

I'm willing to believe this may be a better approach, especially since HealComm's tracking of modifiers is reactive rather than predictive. However from looking at several major frames, most don't seem to do it this way. I am open to writing documentation based on the maintainers feelings to this pull request.

**Comment by Dog** [comment]
@Azilroka I just want to be sure that this means communications should not be passing raw heal values, and the linked example of `GetHealModifier` is not the intent? Regardless I'm open to writing documentation for this project with some clarification.

**Comment by dev7355608** [comment]
This should probably be reverted, because it's a breaking change. The documentation hasn't been updated as well.

**Comment by dev7355608** [comment]
Also `GetHealModifier` needs to be handled separately. We don't want snapshot the debuff effect of, for example, Mortal Strike at the time of casting the heal. Mortal Strike might run out before the heal lands. Or, Mortal Strike could be applied after the casting started. We want to be able to dynamically update the healing prediction. That's why we have the `HealComm_ModifierChanged` event.

**Pull request merged**
